// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNIooCgDTy67zfKAh5b3DE54LpXHSZWnk',
    appId: '1:162393159264:web:9e4244839644073d4bf505',
    messagingSenderId: '162393159264',
    projectId: 'jobai-a1c15',
    authDomain: 'jobai-a1c15.firebaseapp.com',
    storageBucket: 'jobai-a1c15.appspot.com',
    measurementId: 'G-SRY75F6S9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2syuJN-N_vC3rlt5BH4n8_91LyHCsQSw',
    appId: '1:162393159264:android:3dc6af9ecf4b532e4bf505',
    messagingSenderId: '162393159264',
    projectId: 'jobai-a1c15',
    storageBucket: 'jobai-a1c15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6WlMFOg3HVqqCcWuJKwg_HU41tpKQxV8',
    appId: '1:162393159264:ios:2446576507e6f0b34bf505',
    messagingSenderId: '162393159264',
    projectId: 'jobai-a1c15',
    storageBucket: 'jobai-a1c15.appspot.com',
    iosClientId: '162393159264-3pjiv4brj9mcfuvae0ir5vejkdeaae6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJobSeeking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6WlMFOg3HVqqCcWuJKwg_HU41tpKQxV8',
    appId: '1:162393159264:ios:2446576507e6f0b34bf505',
    messagingSenderId: '162393159264',
    projectId: 'jobai-a1c15',
    storageBucket: 'jobai-a1c15.appspot.com',
    iosClientId: '162393159264-3pjiv4brj9mcfuvae0ir5vejkdeaae6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJobSeeking',
  );
}
